### ISSUE TITLE
请升级dio依赖至V4.0.0

### ISSUE THREAD

**Issue by XinwenCheng** [LaoMengFlutter/flutter-do#62]
`flutter_app_upgrade`上一次更新是2020年6月，依赖的dio版本是`3.0.9`。现在dio已经更新至`4.0.0`，各常用插件也已经逐步升级支持，但是`flutter_app_upgrade`还停留在`3.0.9`，就会造成其它插件无法正常进行`pub get`，只能倒退回老版本。

请`flutter_app_upgrade`维护者尽快考虑升级`dio`依赖，非常感谢！

**Comment by bamboo407** [comment]
支持，目前也存在这个问题

**Comment by chenxiubin** [comment]
支持，目前也存在这个问题

**Comment by jingzhanwu** [comment]
支持，请升级flutter2.0吧，dio也升级到4.0.0

**Comment by cgzcgb** [comment]
flutter最新版本已经是2.8了

**Comment by XinwenCheng** [comment]
不等了，等不起，自己fork吧。
